name: test_grading
on:
  pull_request_target:
    types: [opened]
    paths:
    - 'static/admin/userdata/tests/**.yml'


# verify course registration
# abstract pr file body from pr event
# curl answer key file
# compare reponse body values with answer key values
# prepare grading report
# post grading report to member profile repo
# if passing grade, update member course record page
# post message with link to grading report to pr ticket
# close pr ticket

jobs:
  job_verify_membership:
    name: verify_membership
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.ismember.outputs.ismember }}
    steps:
      - name: review event details
        run: |
          env
          cat /home/runner/work/_temp/_github_workflow/event.json
      - name: set source org/repo as org_repo
        run: |
          echo $(echo org_repo="$GITHUB_REPOSITORY") >> $GITHUB_ENV
          echo $org_repo
      - name: curl member record file
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "https://raw.githubusercontent.com/modernapsninja/admin-private/main/userdata/members/${{ github.event.sender.login }}_${{ github.event.sender.id }}.json" \
          -o /tmp/raw_member_record_curl.json
      - name: check if member record exists
        run: |
          cat /tmp/raw_member_record_curl.json
          if [ $(wc -l <"/tmp/raw_member_record_curl.json") -ge 2 ]
          then
            echo ismember=true >> $GITHUB_ENV
            echo "the requesting user is a member"
          else
            echo ismember=false >> $GITHUB_ENV
            echo "the requesting user is not a member"
          fi
          echo $ismember
      - id: ismember
        if: env.ismember == 'true'
        run: echo "::set-output name=ismember::true"
      - name: if not member, post message to pr
        if: env.ismember == 'false'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event": "COMMENT", "body": "@${{ github.event.sender.login }} You must first register as a member at https://modernapps.ninja before you can register for a course. Please open a new registration request after you have completed the modernapps.ninja member registration. This Pull Request will now be closed, thank you!"}' \
          "https://api.github.com/repos/${{ env.org_repo }}/pulls/${{ github.event.number }}/reviews" \
          -o /tmp/pr_comment_post_response.json
          cat /tmp/pr_comment_post_response.json
      - name: if not member, close pr
        if: env.ismember == 'false'
        run: |
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ env.org_repo }}/pulls/${{ github.event.number }}" \
          -o /tmp/close_pr_response.json
          cat /tmp/close_pr_response.json
  job_course_registration:
    name: course_registration
    needs: job_verify_membership
    runs-on: ubuntu-latest
    if: needs.job_verify_membership.outputs.ismember == 'true'
    steps:
      - name: review event details
        run: |
          env
          cat /home/runner/work/_temp/_github_workflow/event.json
      - name: install yq
        run: |
          sudo snap install yq
      - name: set org/repo as org_repo
        run: |
          echo $(echo org_repo="$GITHUB_REPOSITORY") >> $GITHUB_ENV
          echo $org_repo
      - name: curl member record file
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "https://raw.githubusercontent.com/modernapsninja/admin-private/main/userdata/members/${{ github.event.sender.login }}_${{ github.event.sender.id }}.json" \
          -o /tmp/raw_member_record_curl.json
      - name: curl file list for pr
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "https://api.github.com/repos/${{ env.org_repo }}/pulls/${{ github.event.number }}/files" \
          -o /tmp/pr_file_list.json
      - name: set envar pr_filename as filename value
        run: |
          cat /tmp/pr_file_list.json | jq -r '.filename' > /tmp/pr_filename
          echo pr_filename=$(cat /tmp/pr_filename) >> $GITHUB_ENV
      - name: set raw link to pr file as envar pr_raw_file_url
        run: |
          cat /tmp/pr_file_list.json | jq -r '.raw_url' > /tmp/pr_filename
          echo pr_raw_file_url=$(cat /tmp/pr_filename) >> $GITHUB_ENV
      - name: curl the pr file
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "${{ env.pr_raw_file_url }}" \
          -o /tmp/pr_raw_file.yml
      - name: curl the answer key
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "https://raw.githubusercontent.com/modernapsninja/admin-private/main/appdata/courses/${{ github.event.base.repo.name }}/key.${{ env.pr_filename }}.raw" \
          -o /tmp/key.${{ env.pr_filename }}.raw
      - name: curl the test metadata file
        run: |
          curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          "https://raw.githubusercontent.com/modernapsninja/admin-private/main/appdata/courses/${{ github.event.base.repo.name }}/meta.${{ env.pr_filename }}" \
          -o /tmp/meta.${{ env.pr_filename }}
      - name: decode answer key file
        run: |
          cat /tmp/key.${{ env.pr_filename }}.raw | base64 -d > /tmp/key.${{ env.pr_filename }}
      - name: diff pr_raw_file.yml against test answer key
        run: |
          diff -iwB /tmp/key.${{ env.pr_filename }} /tmp/pr_raw_file.yml > /temp/diff_results_raw
      - name: clean diff results file
        run: |
          awk '/^/' /temp/diff_results_raw | sed -e 's/^< //g' > /tmp/wrong_answers
      - name: set question count value for total questions and wrong_answer questions
        run: |
          echo total_question_count=$(grep -ci /tmp/key.${{ env.pr_filename }}) >> $GITHUB_ENV
          echo wrong_question_count=$(grep -ci /tmp/wrong_answers) >> $GITHUB_ENV
      - name: set envar percent_correct as percent correct by comparing line count of diff results to line count of answer key
        run: |
          echo percent_correct=$(bc <<< 'scale=2; (1-('${{ env.wrong_question_count }}'/'${{ env.total_question_count}}'))*100') \
          | sed 's/\..*//g' >> $GITHUB_ENV
      - name: set envar passing_percent
        run: echo passing_percent=$(yq e '.passing_percent' /tmp/meta.${{ env.pr_filename }}) >> $GITHUB_ENV
      - name: set envar passing_grade=true/false
        run: |
          if [ ${{ env.percent_correct}} -ge ${{ env.passing_percent }}]
          then
            echo "passing_grade_phrase=You Passed the Test!" >> $GITHUB_ENV 
            echo passing_grade=true >> $GITHUB_ENV
          else
            echo "passing_grade_phrase=You Did Not Pass the Test. Please review the incorrect answers below and retake the test when ready" >> $GITHUB_ENV
            echo passing_grade=false >> $GITHUB_ENV
          fi
      - name: prepare grade report
        run: |
          echo "Member Grade Report for ${{ github.event.sender.login }} for ${{ env.pr_filename }}" > /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "--------" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "Test Result: ${{ env.passing_grade_phrase }}" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "Minimum Passing Percentage: ${{ env.passing_percent }}%" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "Percent of Questions You Answered Correctly: ${{ env.percent_correct }}%" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "--------" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          echo "The following questions were incorrect in your test submission:" >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
          cat /tmp/wrong_answers >> /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}
      - name: encode grade report with base64 -w 0
        run: cat /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }} | base64 -w 0 > /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}.base64
      - name: post grade report to member repo
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"message": "Posting Member Grade Report grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}", "content": "'$(cat /tmp/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}.base64)'"}' \
          "https://api.github.com/repos/modernappsninjas/${{ github.event.sender.login }}/contents/static/userdata/courses/${{ github.event.base.repo.name }}/grade_report.pr${{ github.event.number }}.${{ env.pr_filename }}" \
          -o /tmp/member_grade_report_post_response.json
          cat /tmp/member_grade_report_post_response.json
      - name: if passing, update member course card
      - name: if passing, post message to pr
      - name: if not passing, post message to pr
      - name: close pr

          
          
          






      - name: CLOSE pull request
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"commit_title": "Course Registration for ${{ github.event.sender.login }}"}'                                                        \
          "https://api.github.com/repos/${{ env.org_repo }}/pulls/${{ github.event.number }}/merge" \
          -o /tmp/course_registration_post_response.json
          cat /tmp/course_registration_post_response.json
      # - name: curl member record file
      #   run: |
      #     curl -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
      #     "https://raw.githubusercontent.com/modernapsninja/admin-private/main/userdata/members/${{ github.event.issue.user.login }}_${{ github.event.issue.user.id }}.json" \
      #     -o /tmp/raw_member_record_curl.json
      # - name: check if member record exists
      #   run: |
      #     cat /tmp/raw_member_record_curl.json
      #     if [ $(wc -l <"/tmp/raw_member_record_curl.json") -ge 2 ]
      #     then
      #       echo ninja_org_member=true >> $GITHUB_ENV
      #     else
      #       echo ninja_org_member=false >> $GITHUB_ENV
      #     fi
      #     echo $duplicate_request
      # - name: extract user preferred email and set as member_email
      #   run: |
      #     echo $(echo member_email=$(echo $(cat /tmp/issuebody.json | jq '.preferredEmailAddress' | sed 's/"//g' ))) >> $GITHUB_ENV
      #     echo $member_email
      # - name: extract user id and set as member_id # in future need to update this file to ensure a common env is used consistently for the same variable data
      #   run: |
      #     echo $(echo member_id="${{ github.event.issue.user.id }}") >> $GITHUB_ENV
      #     echo $member_id
      # - name: extract user login and set as member_id # in future need to update this file to ensure a common env is used consistently for the same variable data
      #   run: |
      #     echo $(echo member_id="${{ github.event.issue.user.login }}") >> $GITHUB_ENV
      #     echo $member_id
      # - name: set token as GITHUB_OAUTH_TOKEN
      #   run: |
      #     echo $(echo GITHUB_OAUTH_TOKEN="${{ secrets.NINJABOTGURU }}") >> $GITHUB_ENV
      #     echo $GITHUB_OAUTH_TOKEN
      # - name: set organization name as org_login
      #   run: |
      #     echo $(echo org_login="${{ github.event.organization.login }}") >> $GITHUB_ENV
      #     echo $org_login
      # - name: create member registration file for upload
      #   run: |
          
      # - name: push new member record to static/userdata/registrations/
      #   if: env.duplicate_request == 'false'
      #   run: |
      #     curl -X PUT \
      #     -H "Authorization: token ${{ secrets.NINJABOTGURU }}" \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -d '{"message": "Updating Member Record File For ${{ github.event.issue.user.login }}", "content": "'$(cat /tmp/issuebody.json | base64 -w 0 )'"}'                                                        \
      #     "https://api.github.com/repos/modernappsninja/admin-private/contents/userdata/members/${{ github.event.issue.user.login }}_${{ github.event.issue.user.id }}.json" \
      #     -o /tmp/member_record_post_response.json
      #     cat /tmp/member_record_post_response.json
      # - name: clone modernappsninja.github.io repo
      #   run: |
      #     git clone https://${{ secrets.NINJABOTGURU }}:x-oauth-basic@github.com/modernappsninja/modernappsninja.github.io.git
      #     cd modernappsninja.github.io
      #     pwd
      # - name: curl orgteamregapicall.sh and make executable
      #   if: env.duplicate_request == 'false'
      #   run: |
      #     curl https://modernapps.ninja/admin/orgteamregapicall.sh -o /tmp/orgteamregapicall.sh
      #     sudo chmod +x /tmp/orgteamregapicall.sh
      # - name: make org and team invite api call
      #   if: env.duplicate_request == 'false'
      #   run: |
      #     /tmp/orgteamregapicall.sh
      # - name: create hub config file
      #   run: |
      #     echo "---" > ~/.config/hub
      #     echo "github.com: " >> ~/.config/hub
      #     echo "- oauth_token: ${{ secrets.NINJABOTGURU }}" >> ~/.config/hub
      #     echo "  user: modernappsninjabot" >> ~/.config/hub
      #     cat ~/.config/hub
      # - name: if duplicate_request true, send email duplicate registration notice
      #   if: env.duplicate_request == 'true'
      #   uses: dawidd6/action-send-mail@v2
      #   continue-on-error: true
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: modernappsninjabot@gmail.com
      #     password: ${{secrets.NINJABOT_MAIL_PASSWORD}}
      #     to: ${{ env.requesting_user_email }}
      #     from: modernappsninjabot@gmail.com
      #     subject: Your ModernApps Ninja User Registration is a Duplicate
      #     body: |
      #       Your registration request with ModernApps Ninja for github user ${{ github.event.issue.user.login }} was recieved, but was found to be a duplicate request.
      #       When you open a registration request, the github account you are logged in as at the time is used for the registration request.
      #       If you intended to request registration for a different account, please log in with the desired account first, and then open a new registration request ticket.
      #       If you believe this message to be in error, or are having issues with your account registration, please open a support request ticket at https://github.com/modernappsninja/modernappsninja.github.io
      # - name: if duplicate_request false, send email registration complete notice
      #   if: env.duplicate_request == 'false'
      #   uses: dawidd6/action-send-mail@v2
      #   continue-on-error: true
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: modernappsninjabot@gmail.com
      #     password: ${{secrets.NINJABOT_MAIL_PASSWORD}}
      #     to: ${{ env.requesting_user_email }}
      #     from: modernappsninjabot@gmail.com
      #     subject: An invite has been sent to ${{ github.event.issue.user.login }} to join the ModernApps Ninja Github org.
      #     body: |
      #       Your registration request with ModernApps Ninja for github user ${{ github.event.issue.user.login  }} was recieved and an invitation to join the org has been sent to the email associated with the ${{ github.event.issue.user.login }} is dupicate, closing" --message "The github user ${{ github.event.issue.user.login }} Github account.
      #       Before registration can be finalized for the requesting github account, you will need to view the invitation email sent by github to the email address associated with the ${{ github.event.issue.user.login }} is dupicate, closing" --message "The github user ${{ github.event.issue.user.login }} Github account.
      #       After you accept the invitation for the account to join the ModernApps Ninja Github account, a workflow will be triggered that will complete your user registration and setup your member profile page, and an email will be sent to this address when the process is complete. 
      #       Thank you for your participation and welcome to the ModernApps Ninja Community!
      # - name: if duplicate_request true, append message to issue ticket and close ticket
      #   if: env.duplicate_request == 'true'
      #   run: |
      #     cd modernappsninja.github.io
      #     hub issue update ${{ github.event.issue.number }} --message "registration request for user ${{ github.event.issue.user.login }} is dupicate, closing" --message "The github user ${{ github.event.issue.user.login }} is already registered. This request has been marked as a dupicate request and will be closed."
      #     hub issue update ${{ github.event.issue.number }} -s closed
      # - name: if duplicate_request false, append message to issue ticket and close ticket
      #   if: env.duplicate_request == 'false'
      #   run: |
      #     cd modernappsninja.github.io
      #     hub issue update ${{ github.event.issue.number }} --message "registration request for user ${{ github.event.issue.user.login }} has been processed" --message "The github user ${{ github.event.issue.user.login }} has been sent an invite to join the modernapps ninja org, and this issue ticket will now be closed."
      #     hub issue update ${{ github.event.issue.number }} -s closed
      # - name: transfer issue ticket to admin-private
      #   run: |
      #     cd modernappsninja.github.io
      #     hub issue transfer ${{ github.event.issue.number }} ${{ github.event.organization.login }}/admin-private